### ISSUE TITLE
Type error when TailwindVariant style contains boolean

### ISSUE THREAD

**Issue by maracht-nn** [nextui-org/tailwind-variants#105]
**Describe the bug**
Receive type error when TailwindVariant style contains boolean.

**To Reproduce**

1. Have boolean in the tv style
2. Use tv style in `.tsx` file
3. See type error saying `Type boolean is not assignable to string | number | undefined`

**Expected behavior**
There should not be any errors. The boolean should be converted to string under the hood. Or the type should accept boolean.

**Screenshots**

The setting on tv containing booleans:
![image](https://github.com/nextui-org/tailwind-variants/assets/107906058/3951587f-9728-46f5-ac01-b186196cbae3)

The type error received when using the tv style:
![image](https://github.com/nextui-org/tailwind-variants/assets/107906058/09bce3fd-ac81-4699-b19c-36f8160b2ae0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- macOS 13.5.2
- Chrome
- Typescript 4.9.4
- tailwind-variants: 0.1.13
- typescript-eslint/eslint-plugin: 5.60.1,
- typescript-eslint/parser: 5.47.0,

**Additional context**
Please let me know if there is any questions. Thank you.

**Comment by mskelton** [comment]
I'm not able to reproduce this, please try upgrading to the latest version or provide a code sandbox link that reproduces the error.

**Comment by maracht-nn** [comment]
My bad, I found the issue on my side. I was trying to abstract the function and missed passing the correct type. After using {TV} from 'tailwind-variants', everything's working perfectly.

Sorry for the oversight, and thanks for your patience! 🙏
