### ISSUE TITLE
Responsive variants do not work with ﻿`theme()`

### ISSUE THREAD

**Issue by h-jennings** [nextui-org/tailwind-variants#107]
**Describe the bug**
Using an arbitrary value that references the `theme()` function appears to break the `withTV` transformer's ability to generate classes for responsive variants. Example: `w-[theme(spacing.32)]`.   

**To Reproduce**

1. Go to https://codesandbox.io/p/sandbox/zqqlg2?file=%2Fsrc%2FApp.tsx%3A1%2C1
2. View `App.tsx` on `:L23` the `large` variant that uses the (valid) arbitrary value syntax
3. See classes being appropriately applied (`md:w-[theme(spacing.32)]`) but the CSS is never generated.

**Expected behavior**
CSS is successfully generated for the following classes: `md:w-[theme(spacing.32)] md:h-[theme(spacing.32)]`.

**Additional context**
- This syntax is useful for when you'd like to calculate a value relative to another `theme` value like so: `w-[calc(theme(spacing.32)_/_2)]`
- Using arbitrary values syntax that _doesn't_ reference the `theme()` function as defined and commented out on `:L22` appears to work as expected.

**Comment by PatrykWalach** [comment]
Responsive variants do not work with class containing `)`
I created a PR #122

**Comment by mskelton** [comment]
This was fixed by #122
