### ISSUE TITLE
IntelliSense not working on .ts file

### ISSUE THREAD

**Issue by adirizky54** [nextui-org/tailwind-variants#117]
**Describe the bug**
IntelliSense not working when i try to create seperate style on .ts files

**To Reproduce**

1. Follow the [documentation instructions](https://www.tailwind-variants.org/docs/getting-started#intellisense-setup-optional) to enable autocomplete.
2. Create .ts file that contain function tv
3. Notice that the regex loses its reference and stops autocompleting any other available classes.

**Expected behavior**
It would be expected that autocomplete works normally.

**Screenshots**
<img width="925" alt="Screenshot 2023-10-22 at 01 13 42" src="https://github.com/nextui-org/tailwind-variants/assets/24888851/9c4eadfb-7514-4f8c-93db-ddde113f375a">
<img width="925" alt="Screenshot 2023-10-22 at 01 13 53" src="https://github.com/nextui-org/tailwind-variants/assets/24888851/7f1290c9-5420-4903-a7ee-1890a798ba44">

**Comment by mskelton** [comment]
Might be related to this: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/868

**Comment by Alex-Programmer-Bro** [comment]
It works for me while I use vscode.

```json
{
    "tailwindCSS.experimental.classRegex": ["[\"'`](.*?)[\"'`]"]
}
```

<img width="873" alt="image" src="https://github.com/nextui-org/tailwind-variants/assets/115539090/d39e1170-a02e-4e33-9bbc-3ad43804ea31">

**Comment by adirizky54** [comment]
Thanks @Alex-Programmer-Bro i just try that config, now it's work!
