### ISSUE TITLE
Issues with `ClassNameValue` types

### ISSUE THREAD

**Issue by cschroeter** [nextui-org/tailwind-variants#145]
Given this Button component in Solid.js I receive the following type error.

```JSX
import { splitProps, type JSX } from 'solid-js'
import { tv, type VariantProps } from 'tailwind-variants'

export interface ButtonProps
  extends ButtonVariantProps,
    JSX.ButtonHTMLAttributes<HTMLButtonElement> {}

export const Button = (props: ButtonProps) => {
  const [variantProps, buttonProps] = splitProps(props, ['class', 'size'])
  return <button class={styles(variantProps)} {...buttonProps} />
}

type ButtonVariantProps = VariantProps<typeof styles>

const styles = tv({
  base: 'button',
  defaultVariants: { size: 'md' },
  variants: {
    size: {
      sm: 'button--size_sm',
      md: 'button--size_md',
      lg: 'button--size_lg',
    },
  },
})
```

```text
Argument of type 'Pick<ButtonProps, "class" | "size">' is not assignable to parameter of type '({ size?: "md" | "sm" | "lg" | undefined; } & ClassProp<ClassNameValue>) | undefined'.
  Type 'Pick<ButtonProps, "class" | "size">' is not assignable to type '{ size?: "md" | "sm" | "lg" | undefined; } & { class: ClassNameValue; className?: undefined; }'.
    Type 'Pick<ButtonProps, "class" | "size">' is not assignable to type '{ class: ClassNameValue; className?: undefined; }'.
      Property 'class' is optional in type 'Pick<ButtonProps, "class" | "size">' but required in type '{ class: ClassNameValue; className?: undefined; }'.ts(2345)
const variantProps: Pick<ButtonProps, "class" | "size">
```

To simply the issue even further:

```tsx
interface Foo {
  class?: string
}

export const App = () => {
  const variantProps: Foo = {}
  styles(variantProps) // error
}
```

This gives the same error, but I think the type is perfectly fine?!

**Comment by mskelton** [comment]
@cschroeter I wasn't able to reproduce this locally. Could you create a reproduction repo or code sandbox that shows the error?

**Comment by cschroeter** [comment]
Sure here you go: https://codesandbox.io/p/devbox/white-wildflower-lkhg3d?file=%2Fsrc%2FApp.tsx%3A9%2C33

**Comment by mskelton** [comment]
@jrgarciadev Looks like this issue is related to the `ClassProp` type.

```ts
export type ClassProp<V extends unknown = ClassValue> =
  | {
      class: V;
      className?: never;
    }
  | {class?: never; className: V}
  | {class?: never; className?: never};
```

Technically the `ClassProp` type is not accurate based on how the runtime works. To fix this issue we could relax the type to support passing both a class and className at the same time. I understand why that's not ideal given that in most cases, it would be confusing to pass both, but would simplify it a bit and also fix bugs like this one.

```ts
export type ClassProp<V extends unknown = ClassValue> = {
  class: V;
  className?: V;
};
```

**Comment by cschroeter** [comment]
@mskelton 

Not tested but couldn't that work?

```typescript
export type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never }
export type XOR<T, U> = T | U extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U

export type ClassProp<V extends unknown> = XOR<{ class: V }, { className: V }>
```

**Comment by mskelton** [comment]
@cschroeter Even with that code, the same issue occurs. The issue is that `Foo` is specifying both class and className, so there isn't a way to support that and also enforce that you only pass one of the two props.

**Comment by cschroeter** [comment]
@mskelton got it. Yeah so I guess relaxing the types is a good solution after all.

**Comment by akomm** [comment]
I had an issue with this in cva library and did provide a fix for the typing. The issue is the ambiguity of union when both elements of the union can be undefined. 

https://github.com/joe-bell/cva/issues/202

**Comment by mskelton** [comment]
@akomm The type of `ClassProp` in tailwind-variants already supports the 4 use cases that you showed in the TS Playground link. The issue is when you define both `class` and `className`.

@cschroeter My recommendation would be to update your component to always use `className` for your `Button` component as right now your type supports both it would seem.

**Comment by akomm** [comment]
Are you sure? Here reproduction with only using className: [TS Playground](https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBAbxgNwDRxgTzAUzgNQEMphCA7GABSgjAGcBfOAMxpDgCIZDgAbAd2BkAJgFpkxUhTocAULIDGEMnXjIARhAAecALwZkACgSy4ZuOsJ0cALk7NeOHQ6eilvOQwCU8rLjjUtHR6BJLkVDT0ADx+OBDMcBraAHxwAGSIpuYKABZ8wlA4ZAD8dgBKOIQKMAB0FVUwAHIQwjhZZgq8VnSNhCA4pXCqJGQA5rIM8koq8PgAQtrlldU1AGIAwlGB9Kn6xrn5hWToNadgkYxeeqmG7XBRwsDIcJ3dvf26CElahudBXgxkggDrwCkUGFEAPSPZDJWQ+WSQyEYPLBQogCDIHDBPrqYCjACuwCw6HUBPgxOC-Gg1kUylUBAWWgAgrwYDgoGRCDAnrY4PUVhsthddnB9l06D0+jh0CCwcc4Kcan96N5rmK7g8ni8JVKPl9ND9gbr3jLFWcLt5AcC8qCjhDoU84V4gA)

I've also added a VBoxVariant component in the example, which shows how it is possible that you maybe did not notice the problem. Because it only becomes apparent if you pass through the className in a specific way. Or did I miss something?

**Comment by akomm** [comment]
Here is using the ClassProp from tailwind-variants: [TS Playground](https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBDAnmApnA3gYQDYEMDO+AartgK4oC+cAZlBCHAEQy7DYDuwAdgCYC0AN1xRgubjHxMAUNKSo4OAvgAK9MAB4icFAA8YKPvjhluAa24QO3OAF5FeQiXIoAfHelw4AHwyevAQDGjvgAXHBEANz+AXDBygByuCAoAPzh3CiCKFDRsZT+vujxhOlwmdm5cSFJKeFEBV5FJfhlFTmR1YnJaRlZOZTRsrwo8VBoNKaBMMAQNgb4MEqEahCaACo6+oa8xsuq6q4AFGDqYXDrAJThghDAvMOjeONxc4twp2v4AIzhxTU9MqLUTcADmBRGYzQgTe8E+YHwACY-i0gTAQeDpJDntDYR8zgBmFEAupwYE8THYkS47jveH4AAsxOU4XJYIhT2pr1pcLOAFZmYRWeiKQAaLqEWooYUYjlQ7l0s4ANkFrRlYol+Cl6vZWM5LxhPPxXwA7KqdaDxS0pWjZXr5YbFV8ABzmskisFWkm9d126QAen9cBAEDI+BQ-AglQQEDJKDQMAAFmgeDQcuNeAhkGgIDQLrJA2TE6HsJnLPB09A5ChFvtVmATmdvpc4IXNvZ-t0UraKT4THwUDQeCheAUFksQvXG19ES223YMKiLX3TCMh5lR9Xa5P1NOEQS50H24vvRaxzWJ8op-SGYeLgvO0LfRSCgGg-hi2RSzooPQoFvLxWXd6T5S4ALrYDlTA8cILWPd8BNaCL1ght6WdS4gA)
Here fixing the ClassProp from tailwind-variants: [TS Playground](https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBDAnmApnA3gYQDYEMDO+AartgK4oC+cAZlBCHAEQy7DYDuwAdgCYC0AN1xRgubjHxMAUNKSo4OAvgAK9MAB4icFAA8YKPvjhluAa24QO3OAF5FeQiXIoAfHelw4AHwwBjR3wAfgAuOG4UQRQoAG44AOUAOVwQFDCiSk8ff0DQuCI4hMJk1LyIqKhKGNlpXhQEqDQaUz8YYAgbA3wYJUI1CE0AFR19Q15jXtV1VwAKMHV8MMGASjDBCGBeWTqGtD8O7rh5gfwARjD0IvwSlDzu0W4Ac0ydvEb4g-hjsHwAJgurncYA9nrV6m89p8jgsAMwAwI3ML3Hig14iSHcQ7ffAAFnhyiRwJRL3B6I+mK+CwArPjCISQQAaeIIlJpODIp4k3bkrELABstOC9JRTKuiPZRM5YO5+wp0JOAHZBcKnqKWaUVajSe9ZbyTgAOZUSxnMpKsoEgzLSAD01rgIAgZHwKH4EAqCAg7JQaBgAAs0DwaNFGrwEMg0BAaHBBrJbezfY7sKHLPBg9A5ChupN+mA5gtTss4HHhvZLurbprsqY6jQeCheJkuj1Ajm8ydfoXi3YcsoLSiq3wULWIg2M1mW+o2z8YZ27SWe8VWZrG5nm8pW9icbPo92ywTjcTY3b8AmyEmdFB6FAx2u+pPsVTljfs-f+U+my+BlP8Ar36vP7m2L6ssQA)

Does it miss some cases maybe?

**Comment by cschroeter** [comment]
@mskelton,

Thank you for your efforts in addressing this issue. I appreciate the time you've invested. However, the solution you proposed doesn't seem to align with Solid.js's approach, as demonstrated in the example I've shared below. This example showcases a basic button implementation in Solid.js using the Solid JSX namespace.

In Solid.js you don't use `className` you either use `classList` or `class` so your suggestion is kinda an anti-pattern for this framework.

```
import { splitProps, type JSX } from 'solid-js'
import { tv, type VariantProps } from 'tailwind-variants'

export interface ButtonProps
  extends ButtonVariantProps,
    JSX.ButtonHTMLAttributes<HTMLButtonElement> {}
    
export const Button = (props: ButtonProps) => {
  const [variantProps, buttonProps] = splitProps(props, ['class', 'size'])
  return <button class={styles(variantProps)} {...buttonProps} />
}
type ButtonVariantProps = VariantProps<typeof styles>
const styles = tv({
  base: 'button',
})
```

**Comment by mskelton** [comment]
@akomm I had a mistake in my testing. After more testing, the solution from CVA does indeed work for tailwind-variants as well, so I've put up a PR with this fix.

**Comment by cschroeter** [comment]
@mskelton anything I can help to push this over the finish line?

**Comment by akomm** [comment]
@cschroeter

@mskelton has already made a PR a while ago:
https://github.com/nextui-org/tailwind-variants/pull/147

But someone needs to review and confirm it.

**Comment by mskelton** [comment]
@cschroeter @akomm Just waiting on a review from @jrgarciadev.  The project is definitely not dead, but Junior and the NextUI team have had a lot on their plate lately with the launch of NextUI Pro.
