### ISSUE TITLE
Cannot use the `cn` utility function without passing any parameters.

### ISSUE THREAD

**Issue by bonizario** [nextui-org/tailwind-variants#157]
**Describe the bug**
The returned function of `cn()` expects an optional configuration object as a parameter.

Calling it without passing anything raises an error.

**To Reproduce**

1. Call the `cn` function without passing parameters e.g.: `cn('text-white')()`.
2. Error raised.

**Expected behavior**
It should be possible to call the `cn` function without passing a configuration object.

**Screenshots**
![image](https://github.com/nextui-org/tailwind-variants/assets/56419828/27e958f3-a905-480f-966d-be64fd48e85f)

**Desktop (please complete the following information):**

- OS: Linux Mint 21.2 Cinnamon
- Browser: Chrome
- Version: Version 121.0.6167.160 (Official Build) (64-bit)

**Comment by mskelton** [comment]
Closing per discussion in the PR. Consider `cnBase` and `cn` as deprecated given their use is intended to be internal only.

**Comment by akomm** [comment]
That doesn't make any sense TBH.

Then you shouldn't use tailwind-merge under the hood. People will use both variants and something like cn / clsx. Now need to think how to sync its behavior with your library. Why not passing through what you have under the hood out and force to replicate / duplicate it on the user side?
