### ISSUE TITLE
Only Last Color Variant Applied When Combining Text Size and Color Variants

### ISSUE THREAD

**Issue by GabeConsalter** [nextui-org/tailwind-variants#166]
**Describe the bug**
Hello everyone, I've been using tailwind-variants and noticed a possible issue. When trying to use one variant to determine the text size and another variant to determine the text color, only the last color variant is applied in the final result, perhaps due to the className being the same with text-*.

This example code:
![image](https://github.com/nextui-org/tailwind-variants/assets/6640360/352443f3-659a-42da-959c-f6f85ba4da35)

**To Reproduce**

1. Create a scenario where you use tailwind-variants.
2. Attempt to apply one variant to determine the text size.
3. Apply another variant to determine the text color.
4. Notice that in the final result, only the color variant applied last is taking effect.

**Expected behavior**
When combining text size and color variants using tailwind-variants, both variants should be applied successfully to the text, resulting in the specified size and color. Currently, only the last color variant is taking effect, and the expected behavior is to have both variants applied simultaneously.

**Screenshots**
![image](https://github.com/nextui-org/tailwind-variants/assets/6640360/874a4f13-ba44-46e2-859b-4d73a92be7c1)
The text size variant was not applied.

**Desktop (please complete the following information):**

- OS: macOS
- Browser chromium
- Version 122.0.6261.94

**Additional context**
I conducted a test using the class-variance-authority library, and there was no occurrence of the mentioned problem.

This example code:
![image](https://github.com/nextui-org/tailwind-variants/assets/6640360/e3b98a87-d044-4a6c-9a9c-099c2d090e82)

Result:
![image](https://github.com/nextui-org/tailwind-variants/assets/6640360/8711170f-23cd-4244-9080-5a96141b9fbb)
The text size variant was applied.

**Comment by mskelton** [comment]
This is not a tailwind-variants bug, rather you'll need to configure tailwind-merge with your custom colors so it knows how to merge the classes properly.  `cva` doesn't use tailwind-merge which is why it doesn't have the same issue.

You can read about configuring tailwind merge in the docs:

- https://www.tailwind-variants.org/docs/config#config-options
- https://github.com/dcastil/tailwind-merge/blob/v1.8.1/docs/configuration.md

**Comment by mskelton** [comment]
@GabeConsalter I posted links in my comment above.
