### ISSUE TITLE
how to config vscode to show autocomplete 

### ISSUE THREAD

**Issue by agileago** [nextui-org/tailwind-variants#17]
there is no autocomplete suggestion

![image](https://user-images.githubusercontent.com/11799110/219642055-18735b5c-97fd-4b18-bc0b-55fe6e630405.png)

**Comment by jrgarciadev** [comment]
Hey @agileago did you add this configuration to your vscode `settings.json` ?

```json
{
  "tailwindCSS.experimental.classRegex": [
    ["tv\\(([^)]*)\\)", "[\"'`]([^\"'`]*).*?[\"'`]"]
  ]
}
```

Here's you can find more details: https://www.tailwind-variants.org/docs/getting-started#intellisense-setup-optional

**Comment by agileago** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/11799110/219695124-b1af4133-14e2-4b1e-abff-f5e482e64748.png">




perfect !! thanks for your work !!!
