### ISSUE TITLE
Required slots

### ISSUE THREAD

**Issue by DamianGlowala** [nextui-org/tailwind-variants#171]
Currently, there doesn't seem to be a way (or it isn't documented yet) to enforce specific set of slots on the type level.

E.g. given the below type:
```
export type Section =
    | "outer"
    | "wrapper"
    | "label";
```

I'd like to be able to somehow make `tv` fn aware of them and enforce their presence (+ provide autocompletion).

**Comment by mskelton** [comment]
I'm not sure I understand the use case. Why do you need to specify they are required? Isn't that the same difference as just specifying the slots?

**Comment by DamianGlowala** [comment]
That's the point - enforcing what I _need_ to specify based on an external type holding the names of the slots.

Simplest analogical example would be using `Record<Section, string>` instead of `Record<string, string>` (TypeScript is preventing me here from forgetting sections, typos, or adding unneeded ones - lots of benefits).

**Comment by DamianGlowala** [comment]
That's what I'd imagine:
`tv<Section>({ slots: { <autocompleted based on Section type> } })`

... and this is the root of this change:
`type TVSlots<KeyT extends string> = Record<KeyT, ClassValue> | undefined;`

**Comment by mskelton** [comment]
I really don't see the value here. If you don't define a slot, when you use the returned result and try to use a slot value that doesn't exist, TypeScript will warn. Specifying the types, then specifying them in the actual `tv` call just doesn't make sense and complicates the types more than they need to be.

Closing as not planned.

**Comment by DamianGlowala** [comment]
Current solution:
```
tv({
  slots: {
    ...
  } satisfies Record<Section, ClassValue>
})
```
