### ISSUE TITLE
Custom boxShadow not working with shadow color class

### ISSUE THREAD

**Issue by lauri865** [nextui-org/tailwind-variants#18]
**Describe the bug**
Custom shadows get stripped from the classList when used with a color class.

**To Reproduce**

1. Create a custom boxShadow in tailwind config: `{circle: "0 0px 30px -10px rgba(0, 0, 0, 0.3)"}`
2. Create a tv with variant: `shadow-circle shadow-violet-600`
3. Results in: `hover:shadow-violet-600`, with `shadow-circle` stripped
4. If I remove `shadow-violet-600`, then `shadow-circle remains`

**Expected behavior**
Custom shadows should be usable with shadow color utility classes

Great work on this btw!

**Comment by jrgarciadev** [comment]
Hey @lauri865 thanks for reporting this!, you can pass the prop `twMerge: false` to the `tv` function to disable `tailwind-merge`, here's an example:

https://codesandbox.io/p/sandbox/tv-button-group-forked-kcmrro?file=%2Fsrc%2Fcomponents%2Fstyles%2Fbutton.ts&selection=%5B%7B%22endColumn%22%3A4%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A4%2C%22startLineNumber%22%3A9%7D%5D

We will work on improving the extendability of `tailwind-merge` 

Here's you can find more info about the property I'm talking about: 
https://www.tailwind-variants.org/docs/api-reference#twmerge

**Comment by viktorbonino** [comment]
I'm also having the same problem with and without custom shadows. 
Twmerge alone doesn't do that, cn() seems to not do that, but complex tv() components for some reason remove the shadow class or the color shadow class depending on order and positioning inside the variants/compoundVariants.

**Comment by its-monotype** [comment]
Is it possible to setup a custom tailwind merge for all tv globally, I guess something like wrapped is needed for it. Any examples?

**Comment by adonaicandido** [comment]
Looking for a way to wrap the tv function with a shared twMergeConfig aswell.

tried this but didn't work:

```ts
import { validators } from "tailwind-merge"
import { tv, type TV } from "tailwind-variants"

type Options = Parameters<TV>[0]
export const twVariants = (options: Options) => {
  return tv(options, {
    responsiveVariants: true,
    twMergeConfig: {
      classGroups: {
        "font-size": [
          { text: [validators.isNumber, validators.isArbitraryLength] },
        ],
      },
    },
  })
}
```

`Tailwind Variants Transform Failed: Cannot access 'options' before initialization`

**Comment by mskelton** [comment]
@adonaicandido You can modify the `defaultConfig` variable.

```ts
import { defaultConfig } from 'tailwind-variants'
defaultConfig.twMergeConfig = {
  // ...
}
```

**Comment by adonaicandido** [comment]
This could be documented. Thanks!

**Comment by mskelton** [comment]
PRs opened to add a `createTV` function and another to add `deafultConfig` to the docs:

- #121 
- https://github.com/nextui-org/tailwind-variants-docs/pull/19

**Comment by mskelton** [comment]
The new `createTV` function is released and the new config docs are published!

https://www.tailwind-variants.org/docs/config
