### ISSUE TITLE
cnBase and tailwind-merge

### ISSUE THREAD

**Issue by federicocappellotto97** [nextui-org/tailwind-variants#184]
It looks if i use cnBase classes conflicts are not resolved by tailwind-merge. How can i solve this?

(Another thing, in the docs i find cxBase, but in the library i just find cnBase, is the docs outdated?)

**Comment by mskelton** [comment]
@federicocappellotto97 The docs there were simply outdated. Also, I'm likely going to deprecate `cnBase` as it is intended to be an internal helper only. It's not something I recommend relying on, please install `tailwind-merge` or `clsx` separately.
