### ISSUE TITLE
SSR doesnt seems to work

### ISSUE THREAD

**Issue by flozero** [nextui-org/tailwind-variants#188]
**Describe the bug**

I am building a ui library that is using tailwind variants to be able to use tailwind and responsive props. My application that consume the ui library is SSR. I saw that next ui is not using breakpoints options as they are using an older version than 2.

My problem is that in our react ssr application breakpoints classes doesnt seems to be generated in the css file evne if the final class string is. Is it a tempo issue where the classes are generated to early or something ?

**To Reproduce**

I will try to reproduce a simple repo

**Expected behavior**

An example ssr project that is using tailwind with tailwind variants

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mskelton** [comment]
@flozero Please provide a codesandbox or example repo reproducing the example, very difficult to help if you don't provide us code examples.

**Comment by flozero** [comment]
alright nvm I found my mistake sorry for alarming
