### ISSUE TITLE
Warning: The engine "pnpm" appears to be invalid

### ISSUE THREAD

**Issue by angel-luis** [nextui-org/tailwind-variants#197]
**Describe the bug**

When I run `yarn`, it appears the following warning:
```
warning tailwind-variants@0.1.20: The engine "pnpm" appears to be invalid.
```

**To Reproduce**

1. Install NextUI manually: `yarn add @nextui-org/react framer-motion`
2. Just see the Warning

**Desktop (please complete the following information):**

- OS: MacOS Sonoma 14.5
- Node: 20.14.0

**Expected Behaviour**

I don't have/use `pnpm` so I don't want to see that warning.

**Comment by DavidAmyot** [comment]
+1

**Comment by melodyxpot** [comment]
I got that warning too.
I am using yarn but I am getting that warning. Does someone know about that?
![image](https://github.com/user-attachments/assets/9aaf6206-378e-44f7-8d16-a55c6588551b)

**Comment by tianenpang** [comment]
Hi everyone, it seems this issue exists in yarn v1 🤔 if you're using v1, you can try adding a `.yarnrc` file with the following line
```txt
ignore-engines pnpm
```

If you want to use the stable version, you can run
```base
yarn set version stable
yarn install
```
