### ISSUE TITLE
`tailwind-merge` as opt-in instead of opt-out?

### ISSUE THREAD

**Issue by datner** [nextui-org/tailwind-variants#208]
Hey!
I was considering using this library over `cva` but had noticed that `tailwind-merge` is supposedly baked-in?

`tailwind-merge` is great, but I don't need it or want it as it comes with quite a bit of overhead and interesting behavior.
I know I can turn it off, which is great!!! But I would still bundle it in.

Would it be possible to remove the dependency on `tailwind-merge` and instead accept an optional merge-resolver from the outside?
```ts
import { twMerge } from "tailwind-merge"
const tv = createTV({
  mergeFn: twMerge
  // ...
});
```
It would remove the need to drill in the configuration as well, removing `twMergeConfig` from the interface...

I know it's a big change in the sense that it's user-facing, but if it's acceptable I can open a PR for it

**Comment by mskelton** [comment]
This would be very breaking for the library given that `createTV` is not the primary way tailwind-variants is used. Going to close as not planned.
