### ISSUE TITLE
`defaultVariants` should be ignored by Tailwind IntelliSense

### ISSUE THREAD

**Issue by petvi** [nextui-org/tailwind-variants#25]
I noticed `defaultVariants` properties are being intellisensed by the [TailwindCSS IntelliSense Extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) when using the settings snippet provided in the [docs](https://www.tailwind-variants.org/docs/getting-started#intellisense-setup-optional):
```
{
  "tailwindCSS.experimental.classRegex": [
    ["tv\\(([^)]*)\\)", "[\"'`]([^\"'`]*).*?[\"'`]"]
  ]
}
```

These properties already have the TS types inferred correctly, so I think the RegEx simply needs to be updated to ignore this property.

**Comment by lauritzsh** [comment]
I assume related but also happens for `responsiveVariants` when I do

```ts
  {
    responsiveVariants: ['sm', 'md', 'lg'],
  }
```

<img width="637" alt="image" src="https://user-images.githubusercontent.com/1979410/237047346-177d648b-62cd-4ea5-8439-1e6265ee31e9.png">

We only have three screens so I do this hack for now to silence the warning
```css
@layer base {
  .sm, .md, .lg {}
}
```

**Comment by its-monotype** [comment]
Should be closed by this: https://github.com/francoismassart/eslint-plugin-tailwindcss/pull/232

**Comment by mskelton** [comment]
This is not really feasible given how the Tailwind intellisense extension works, it's basically all or nothing. Even if we constructed a regex that solved it for defaultVariants or responsiveVariants, other places would still inappropriately provide intellisense such as variant/slot names in `compoundSlots` or `compoundVariants`.

Closing as not planned.

**Comment by katerlouis** [comment]
> ```
> {
>   "tailwindCSS.experimental.classRegex": [
>     ["tv\\(([^)]*)\\)", "[\"'`]([^\"'`]*).*?[\"'`]"]
>   ]
> }
> ```
> 
> These properties already have the TS types inferred correctly, so I think the RegEx simply needs to be updated to ignore this property.

How comes the docs have promoted a new regex as of this writing? https://www.tailwind-variants.org/docs/getting-started#intellisense-setup-optional

I find the current proposal far too aggressive as now every string gets intellisensed by tailwind.
