### ISSUE TITLE
Incorrect types inheritance when extending 

### ISSUE THREAD

**Issue by vanpav** [nextui-org/tailwind-variants#44]
**Describe the bug**
When using "extend" prop to compose class names, the prop-types produced in extended TVReturnType aren't correct. Without "boolean" variant, typescript happy, but the type of "props.variant" in the BuyButton component is "string | number | undefined" which looks incorrect too.

**To Reproduce**
```typescript
const baseButton = tv({
  base: "",
  variants: {
    variant: {
      primary: "",
    },
    disabled: {
      true: "",
    },
  },
});

const buyButton = tv({
  extend: baseButton,
});

const Button = (props: VariantProps<typeof baseButton>) => {
  const className = baseButton(props);

  return (
    <div className="flex gap-3">
      <button className={className}>Buy button</button>
    </div>
  );
};

const BuyButton = (props: VariantProps<typeof buyButton>) => {
  const className = buyButton(props);

  return (
    <div className="flex gap-3">
      <button className={className}>Buy button</button>
    </div>
  );
};
```

**Expected behavior**
Props for the "buyButton" inherited properly to let typescript pass without errors and suggest correct variants in autocomplete.

**Screenshots**
<img width="1152" alt="Screenshot 2023-05-03 at 17 58 15" src="https://user-images.githubusercontent.com/2944759/235955678-414249c0-7ad9-4216-b0cb-1dab953981f8.png">
<img width="910" alt="Screenshot 2023-05-03 at 17 58 26" src="https://user-images.githubusercontent.com/2944759/235955704-44f1bc9b-817d-4248-ba1f-9e5d701a0065.png">

**Desktop (please complete the following information):**
- OS: MacOS Ventura 13.3.1

**Additional context**
- Typescript: 5.0.2
- tailwind-variants: 0.1.5

**Comment by eduardodallmann** [comment]
I think I encountered a similar problem. Boolean variant breaks typescript only when it is extended. See the example:

[Codesandbox](https://codesandbox.io/p/sandbox/mystifying-shannon-9h8n8h?file=%2Fapp%2Fcomps%2Fselect.tsx%3A42%2C44)
Fork is required to see the typescript error
