### ISSUE TITLE
typo on Comparison page

### ISSUE THREAD

**Issue by getinnocuous** [nextui-org/tailwind-variants#49]
**Describe the bug**
Theres a typo at the bottom of the Comparison page.

**To Reproduce**

1. Go to [Comparison page](https://www.tailwind-variants.org/docs/comparison#why-tailwind-variants)
2. "That beign said" should be "That being said"

**Expected behavior**

**Screenshots**
![Screenshot 2023-05-11 at 08 08 39](https://github.com/nextui-org/tailwind-variants/assets/9265979/c21c076a-e629-45e1-9dc5-ba14c2804c40)

**Comment by jrgarciadev** [comment]
Fixed, good catch thank you @getinnocuous 🙏🏻
