### ISSUE TITLE
slow down prettier formating in vscode

### ISSUE THREAD

**Issue by mohammadgarmroodi** [nextui-org/tailwind-variants#50]
i created a button component using tailwind variants like this:
const button = tv(
  {
    base: "py-2 px-5 ",
    variants: {
      variant: {
        contained: "rounded-[10px] ",
        outlined: "rounded-[10px]",
        inlined: "bg-transparent ",
      },
    },
  },
  {
    responsiveVariants: ["lg"],
  }
);

type ButtonVariants = VariantProps<typeof button>;

export type IButtonProps = {
  children: React.ReactNode;
} &  ButtonVariants;

but when i use this component ,the prettier extenstion formatting on vscode takes to long ... !
and when i remove tailwind variants from this component,prettier formatting working stable and fast !

![Screenshot (111)](https://github.com/nextui-org/tailwind-variants/assets/39627321/e9ebeb37-c5d3-4862-82cf-fa4073ffae29)

**Expected behavior**
dont break another tools and extenstion like prettier !

- OS: Windows
- Browser Chrome
- Version 113

**Comment by mskelton** [comment]
Closing as not re-producable. This is most likely an issue with Prettier, a prettier plugin, or something else.
