### ISSUE TITLE
Landing page styling bug

### ISSUE THREAD

**Issue by reikrom** [nextui-org/tailwind-variants#51]
**Describe the bug**
Doesn't look right

**To Reproduce**

1. Go to "tailwind-variants.org
2. Mobile view
3. Scroll-x

**Expected behavior**
...

**Screenshots**
![image](https://github.com/nextui-org/tailwind-variants/assets/44064758/7a56bac5-4399-4477-a49b-576fd7c4e1d1)

**Additional context**
`<svg fill="none" height="1018" viewBox="0 0 1210 1018" width="1210" xmlns="http://www.w3.org/2000/svg" class="absolute -z-10 -translate-y-[40%] animate-[appear_1s_ease]">`
is not responsive

**Comment by mskelton** [comment]
This is now fixed.
