### ISSUE TITLE
Typescript errors with `compoundVariants` and boolean values

### ISSUE THREAD

**Issue by omarkhatibco** [nextui-org/tailwind-variants#55]
**Describe the bug**

This issue appears when I updated typescript from `v5.0.4` to `v5.1.3`. 
now when I run the typecehck `tsc --noEmit` I got this error

```bash
src/Button.tsx:19:7 - error TS2322: Type 'true' is not assignable to type 'string | number | symbol | never[] | undefined'.

19       disabled: true,
         ~~~~~~~~


Found 1 error in src/Button.tsx:19

```

this button component is exactly the live example on the documentation [here](https://www.tailwind-variants.org/docs/variants#compound-variants)

**To Reproduce**

1. Go to this [sandbox](https://codesandbox.io/p/github/omarkhatibco/tailwind-variants-tests/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clihiii9w000b3b6lryddcyc4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clihiii9w000d3b6lrcli0g73%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clihiii9w000b3b6lryddcyc4%2522%253A%257B%2522id%2522%253A%2522clihiii9w000b3b6lryddcyc4%2522%252C%2522activeTabId%2522%253A%2522clihin0d600hv3b6lvilgog5f%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clihiii9w000a3b6lphgi1dbu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FButton.tsx%2522%252C%2522id%2522%253A%2522clihin0d600hv3b6lvilgog5f%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clihiii9w000d3b6lrcli0g73%2522%253A%257B%2522id%2522%253A%2522clihiii9w000d3b6lrcli0g73%2522%252C%2522activeTabId%2522%253A%2522clihiirnd008e3b6lws66wexa%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clihiirnd008e3b6lws66wexa%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clihiispo00e23b6lymhzoz8c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
2. open a new terminal and run `pnpm typecheck`

**Expected behavior**
error should not happen

**Additional context**

**Comment by its-monotype** [comment]
I'm facing the same issue, everything was broken when I switched to TS v5.1.3 :(

**Comment by jessyhalife** [comment]
I'm getting an error when trying to use an array for variant

`size: ["sm", "lg"]`

😞
