### ISSUE TITLE
VariantProps are of type `any`

### ISSUE THREAD

**Issue by jpwallace22** [nextui-org/tailwind-variants#56]
**Describe the bug**
When using the VariantProps generic all of the returned types are `any` instead of being literals. 

**To Reproduce**
1. Create a basic `tv` function in Typescript that includes variants.
```ts
const circle = tv({
  variants: {
    size: {
      md: ["w-[580px] h-[580px]"],
      lg: ["w-[1280px] h-[1280px]"],
    },
    contrast: {
      low: ["bg-gray-100", "dark:bg-purple-900"],
      high: ["bg-gray-200", "dark:bg-purple-800"],
    },
  },
  defaultVariants: {
    size: "md",
    contrast: "high",
  },
})
```
2. Import and use the VariantProps generic 
```ts
type CircleType = VariantProps<typeof circle> 
```
3. Check intellisense on either type, or component, and see `any`
![Screen Shot 2023-06-06 at 9 16 56 AM](https://github.com/nextui-org/tailwind-variants/assets/93415734/410ce0c2-a6c0-48a0-8400-0fd7cb6e80ec)
![Screen Shot 2023-06-06 at 9 16 26 AM](https://github.com/nextui-org/tailwind-variants/assets/93415734/a52d470c-a377-423e-8656-e45b2901d88d)

**Expected behavior**
variant props to be literals. ie: `size: 'md' | 'lg'`

**Screenshots**
Screenshots are added above in description

**Desktop (please complete the following information):**

- OS: Mac 12.6.6
- Browser: Not applicable
- Typescript Version: 5.1

**Smartphone (please complete the following information):**

- Device: n/a
- OS: n/a
- Browser: n/a
- Version: n/a

**Additional context**
The actual `tv` function isn't strongly typed either. I can add whatever I want to `defaultVariants` whether its a variant or not.

**Comment by omarkhatibco** [comment]
I would assume it’s TypeScript version, it broke something inside tailwind-variants.

i suggest that you revert to TypeScript v5.0.4

**Comment by its-monotype** [comment]
Yeah I'm facing the same when I'm bumped TS to 5.1.3

**Comment by zwagnr** [comment]
hey I have been having this same issue, and it has really been holding back a project I am working on. 

I just submitted a PR that seems to resolve this if you guys want to take a look! #60

**Comment by AaronPlave** [comment]
@jrgarciadev it looks like this change was rolled back here https://github.com/heroui-inc/tailwind-variants/commit/421a4f3db16799fdfa18ecaa813347da30ada67c the same day that it was merged in. I'm currently experiencing this same issue where the VariantProps are of type `any`. Do you know why this change was rolled back and if there is some other suggested solution? Thanks!
