### ISSUE TITLE
`TWMConfig["twMergeConfig"]` does not allow partial configurations

### ISSUE THREAD

**Issue by ReoHakase** [nextui-org/tailwind-variants#58]
**Describe the bug**

Since the use of `TWMConfig["twMergeConfig"]` is to be passed to `extendTailwindMerge` that takes configs partially, the type of `TWMConfig["twMergeConfig"]` should be also partial.

```js
const twMerge = !isEmptyObject(config.twMergeConfig)
      ? extendTailwindMerge(config.twMergeConfig)
      : twMergeBase;
```
https://github.com/nextui-org/tailwind-variants/blob/main/src/index.js#LL29C24-L29C24

```js
export function extendTailwindMerge(
    configExtension: Partial<Config> | CreateConfigSubsequent,
    ...createConfig: CreateConfigSubsequent[]
) {
    return typeof configExtension === 'function'
        ? createTailwindMerge(getDefaultConfig, configExtension, ...createConfig)
        : createTailwindMerge(
              () => mergeConfigs(getDefaultConfig(), configExtension),
              ...createConfig,
          )
}
```
https://github.com/dcastil/tailwind-merge/blob/main/src/lib/extend-tailwind-merge.ts#LL8C1-L18C2

```ts
export type TWMConfig = {
  /**
   * Whether to merge the class names with `tailwind-merge` library.
   * It's avoid to have duplicate tailwind classes. (Recommended)
   * @see https://github.com/dcastil/tailwind-merge/blob/v1.8.1/README.md
   * @default true
   */
  twMerge?: boolean;
  /**
   * The config object for `tailwind-merge` library.
   * @see https://github.com/dcastil/tailwind-merge/blob/v1.8.1/docs/configuration.md
   */
  twMergeConfig?: TwMergeConfig;
};
```
https://github.com/nextui-org/tailwind-variants/blob/main/src/config.d.ts#L20

**To Reproduce**

1. Install the package
2. Pass `tv` an empty configuration object as shown below:
```js
tv(options, {
    ...config,
    twMerge: true,
    twMergeConfig: {},
  });
```
3. Now you reproduced the type error.

**Expected behavior**

`TWMConfig["twMergeConfig"]` should be typed partially.

```ts
export type TWMConfig = {
  /**
   * Whether to merge the class names with `tailwind-merge` library.
   * It's avoid to have duplicate tailwind classes. (Recommended)
   * @see https://github.com/dcastil/tailwind-merge/blob/v1.8.1/README.md
   * @default true
   */
  twMerge?: boolean;
  /**
   * The config object for `tailwind-merge` library.
   * @see https://github.com/dcastil/tailwind-merge/blob/v1.8.1/docs/configuration.md
   */
  twMergeConfig?: Partial<TwMergeConfig>;
};
```

**Screenshots**
<img width="643" alt="image" src="https://github.com/nextui-org/tailwind-variants/assets/16751535/85ce4232-5c09-410e-a88f-174354bf369f">

**Desktop (please complete the following information):**

All desktop environments

**Smartphone (please complete the following information):**

All smartphone environments

**Additional context**
None

**Comment by ReoHakase** [comment]
I just realized that this issue is a duplicate of https://github.com/nextui-org/tailwind-variants/issues/54
Sorry for interruption🙏

**Comment by its-monotype** [comment]
I'm facing the same issue
