### ISSUE TITLE
Incorrect Types

### ISSUE THREAD

**Issue by Rawnly** [nextui-org/tailwind-variants#59]
**Describe the bug**

**To Reproduce**
Copy paste example code 

```ts
tv({
  base: 'font-bold',
  variants: {
    size: {
      xs: '',
      sm: ''
    },
    flat: {
      true: ''
    }
  },
  defaultVariants: {
    flat: true,

  },
  compoundVariants: []
})
```

**Expected behavior**
No errors

**Screenshots**
![CleanShot 2023-06-09 at 02 33 43@2x](https://github.com/nextui-org/tailwind-variants/assets/16429579/59e6a4d3-212c-4e1d-a8f3-a1dc7fba24e9)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser not relevant
- Version 0.1.6

**Additional context**

**Comment by omarkhatibco** [comment]
#55
