### ISSUE TITLE
TailwindCSS arbitrary values don't work 

### ISSUE THREAD

**Issue by stone89son** [nextui-org/tailwind-variants#63]
Is there any way to configure it?
I want margin-top: 65px,
so I wrote mt-[65px] but it's not working.
Code:
`<main className="container mx-auto max-w-7xl px-6 flex-grow mt-[65px]">`

**Comment by jrgarciadev** [comment]
But you're not using Tailwind Variants there 🤔

**Comment by stone89son** [comment]
Thank to give me time talking, In NextUI, Is there any other way?
