### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by Sliov** [nextui-org/tailwind-variants#65]
Hey there 👋,

First, thank you for making this lib possible, it has great features and coming from `cva`, it feels nice to use slots and the extend prop.

However, as I was refactoring the project to use `tailwind-variants`, I noticed some performance issue...

Here's a repro:
https://github.com/Sliov/cva-tailwind-variants-benchmark

Do you know if that's normal or if there's space for improvement here?

Thank you

**Comment by jrgarciadev** [comment]
Hey @Sliov to have a fair comparison you should disable [tailwind-merge](https://github.com/dcastil/tailwind-merge) on the `tv` function:

example:

```ts
export const avatar = tv({
...variants
}, {
  twMerge: false
});
```

**Comment by mskelton** [comment]
@Sliov The performance has improved since your benchmark, I ran the benchmark this morning and while the performance is not as good as CVA yet, it's closer now than it was when you ran your benchmark.

**Comment by raminrez** [comment]
@mskelton, Could you please share the latest benchmark?

**Comment by mskelton** [comment]
@raminrez Here you go

https://github.com/nextui-org/tailwind-variants/discussions/133

I'm looking to add CVA to the benchmarks to provide better comparison of the two.

**Comment by mskelton** [comment]
Going to close since there is nothing immediately actionable here.
