### ISSUE TITLE
yarn berry PnP build Error

### ISSUE THREAD

**Issue by minsgy** [nextui-org/tailwind-variants#72]
**Describe the bug**
- yarn berry PnP build Error

**To Reproduce**

1. Set up Next.js starter.
2. Run "yarn set version 3.2.3".
3. Run "yarn install".
4. Encounter an error when running "yarn build".

**Expected behavior**

- Expect the "yarn build" command to run successfully and confirm the build.

**Screenshots**

![image](https://github.com/nextui-org/tailwind-variants/assets/60251579/ea4ef13d-2f30-4613-a8f1-a672919adba3)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browse: Chrome
- Version: recent

**Additional context**

- Is there any other way to apply in a Yarn Berry PnP environment? If so, can you guide me through it?

**Comment by rharink** [comment]
I'm running into the same issue with a Bazel build. It is related to the type generation step in the transformer. Maybe we could opt-out of this via config?

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).
