### ISSUE TITLE
declaration file not found

### ISSUE THREAD

**Issue by carlonoelle** [nextui-org/tailwind-variants#80]
**Describe the bug**
Simply installed the package, and immediatly ts server tells me it cannot find the declaration file or the module. Using it in a NextJs project with the following tsconfig:

EDIT: installed tailwind-variant at version `^0.1.10`

<img width="527" alt="image" src="https://github.com/nextui-org/tailwind-variants/assets/13131183/10e13e93-d602-4608-ab73-1f723adc780e">

Here is the error:
<img width="630" alt="image" src="https://github.com/nextui-org/tailwind-variants/assets/13131183/dba42382-7c3d-4130-a201-73d13c05bcf6">

NextJS Version is 13.4.9, but since its TS related i don't think thats the problem.

**Expected behavior**
Typings just working without research.

**Desktop (please complete the following information):**

- OS: MacOS

**Comment by carlonoelle** [comment]
i figured out that the problem is the moduleresolution setting in the tsconfig. When you are using `Node16` or `nodenext`ts cannot find the type declarations.

I have found this Typescript Issue here explaining the issue: https://github.com/microsoft/TypeScript/issues/49160

But i must say i cannot find a way to correct it myself after a couple minutes of trying. Is there a package maker typescript magician around?

**Comment by carlonoelle** [comment]
Found this handy tool, telling us exactly what issue i am experiencing: https://arethetypeswrong.github.io/?p=tailwind-variants%400.1.10

**Comment by carlonoelle** [comment]
Ok last link: https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/InternalResolutionError.md explains the problem, but i cannot get it working. 

Since i unfortunately need node16 resolution i will switch to cva for now, if someone could help me out here it would be much appreciated!

**Comment by Alex-Programmer-Bro** [comment]
@carlonoelle Can you provide a mini repo ?

**Comment by mskelton** [comment]
Closing as not-reproducable.
