### ISSUE TITLE
Link not found in Documentation

### ISSUE THREAD

**Issue by ankursehdev** [nextui-org/tailwind-variants#84]
**Describe the bug**

The link on the Slots Documentation `https://www.tailwind-variants.org/docs/slots#slots-with-responsive-variants` is throwing 404. Please update the link, it is currently referencing to `https://www.tailwind-variants.org/docs/responsive-variants`. 

**To Reproduce**

1. Go to 'https://www.tailwind-variants.org/docs/slots#slots-with-responsive-variants`'
2. Click on 'here' link
3. It will throw the 404 page error

**Expected behavior**

**Screenshots**
<img width="887" alt="Screenshot 2023-07-23 at 5 24 10 PM" src="https://github.com/nextui-org/tailwind-variants/assets/34501847/91aaa662-fad9-4203-b0c8-56e4b4363b19">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by mskelton** [comment]
This is now fixed.
