### ISSUE TITLE
text size and text color overwrites each other

### ISSUE THREAD

**Issue by amirht-dev** [nextui-org/tailwind-variants#93]
**Describe the bug**
text size and text color overwrites each other

```
const button = tv({
  base: 'rounded-sm',
  variants: {
    variant: {
      primary: 'bg-primary text-neutral-white',
      secondary: '',
      tertiary: ''
    },
    size: {
      small: 'py-2 px-6 text-button-small',
      medium: 'py-3.5 px-8 text-button-medium',
      normal: 'py-4 px-8 text-button-normal'
    }
  },
  defaultVariants: {
    variant: 'primary',
    size: 'medium'
  }
})
```

**Expected Result**
"rounded-sm bg-primary py-3.5 px-8 text-neutral-white text-button-medium"

**Result**
"rounded-sm bg-primary py-3.5 px-8 text-button-medium"

**Comment by jrgarciadev** [comment]
Hey, since you're using custom tailwind classes, you need to use a custom tailwind merge config https://github.com/dcastil/tailwind-merge/blob/v1.14.0/docs/configuration.md

To pass a custom tailwind-merge config use the `twMerge` prop.

e.g.

```js
const button = tv({
  base: 'rounded-sm',
  variants: {
    variant: {
      primary: 'bg-primary text-neutral-white',
      secondary: '',
      tertiary: ''
    },
    size: {
      small: 'py-2 px-6 text-button-small',
      medium: 'py-3.5 px-8 text-button-medium',
      normal: 'py-4 px-8 text-button-normal'
    }
  },
  defaultVariants: {
    variant: 'primary',
    size: 'medium'
  }
},
{
 twMerge: YOUR_TW_MERGE_CONFIG
}
)
```

**Comment by wilsonlewis** [comment]
@jrgarciadev is there a way to just disable the tailwind-merge step all together? I don't really care about having conflicting styles and wouldn't mind not having that overhead. Thanks!

**Comment by wilsonlewis** [comment]
@jrgarciadev incredible! Thank you so much!
