### ISSUE TITLE
Putting "text-{color}" class in the same variant as "text-{size}" class removes the color class

### ISSUE THREAD

**Issue by wilsonlewis** [nextui-org/tailwind-variants#94]
**Describe the bug**
Putting "text-{color}" class in the same variant as "text-{size}" class removes the color class

**To Reproduce**

1. Add tokens to tailwind config

```
const config = {
  theme: {
    colors: {
      ...
      white: '#FFFFFF'
    },
    fontSize: {
      ...
      '14': '0.875rem'
    }
  }
}
```

2. Create variant
```
export const button = tv({
  variants: {
    intent: {
      primary: 'text-white text-14',
    },
  },
  defaultVariants: {
    intent: 'primary',
  },
})
```

3. Add to component
```
function Component() {
  return <button className={button()}>Button</button>
}
```

4. Check DOM and notice missing classes

**Expected behavior**
No tailwind classes should be removed

**Screenshots**
Notice "text-emerald" has been removed
<img width="576" alt="Screenshot 2023-08-20 at 8 38 27 PM" src="https://github.com/nextui-org/tailwind-variants/assets/3818588/765e206b-73b2-4443-8323-d6ee9c2dbc45">
<img width="514" alt="Screenshot 2023-08-20 at 8 38 59 PM" src="https://github.com/nextui-org/tailwind-variants/assets/3818588/d4f85441-f64a-4760-8082-0c3bcc45584f">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: chrome
- Version: 115.0.5790.170

**Additional context**

**Comment by jrgarciadev** [comment]
Hi  @wilsonlewis please check this comment

https://github.com/nextui-org/tailwind-variants/issues/93#issuecomment-1685115214
